/**
 * Vercel Serverless Function: Generate PO PDF (ESM)
 *
 * GET /api/po-pdf?id=<po_uuid>
 * Returns a PDF file download.
 *
 * Reads Supabase for PO data, generates PDF with pdfkit.
 */
import { createClient } from '@supabase/supabase-js';
import PDFDocument from 'pdfkit';

const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.VITE_SUPABASE_ANON_KEY;

export default async (req, res) => {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');

  const poId = req.query.id;
  if (!poId) {
    res.status(400).json({ error: 'Missing ?id=<po_uuid>' });
    return;
  }

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    res.status(500).json({ error: 'Supabase not configured' });
    return;
  }

  try {
    const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    const { data: po, error } = await supabase
      .from('purchase_orders')
      .select('*')
      .eq('id', poId)
      .single();

    if (error || !po) {
      res.status(404).json({ error: 'PO not found' });
      return;
    }

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="po-${po.po_number.toLowerCase()}.pdf"`);

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);

    // Title
    doc.fontSize(24).font('Helvetica-Bold').fillColor('#1e293b')
      .text('PURCHASE ORDER', { align: 'center' });
    doc.moveDown(0.3);

    // PO Number
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#3b82f6')
      .text(po.po_number, { align: 'center' });
    doc.moveDown(0.5);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(0.8);

    // Supplier
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#1e293b')
      .text('Supplier:', { continued: true })
      .font('Helvetica').fillColor('#64748b')
      .text(`  ${po.supplier_name}`);
    doc.moveDown(0.3);

    // Date
    const date = new Date(po.created_at).toLocaleDateString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    });
    doc.font('Helvetica-Bold').fillColor('#1e293b')
      .text('Date:', { continued: true })
      .font('Helvetica').fillColor('#64748b')
      .text(`  ${date}`);
    doc.moveDown(0.3);

    // Ship to
    doc.font('Helvetica-Bold').fillColor('#1e293b').text('Ship To:');
    doc.font('Helvetica').fillColor('#64748b')
      .text('Superare Fight Gear LLC')
      .text('Warehouse Fulfillment Center')
      .text('New York, NY 10001');
    doc.moveDown(0.8);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(0.6);

    // Items header
    doc.fontSize(12).font('Helvetica-Bold').fillColor('#1e293b').text('Items Ordered');
    doc.moveDown(0.3);

    if (po.items && po.items.length > 0) {
      const tableTop = doc.y;
      const colX = [50, 260, 370, 445];

      doc.fontSize(9).font('Helvetica-Bold').fillColor('#64748b');
      doc.text('Product', colX[0], tableTop, { width: 210 });
      doc.text('Variant', colX[1], tableTop, { width: 110 });
      doc.text('Qty', colX[2], tableTop, { width: 75, align: 'center' });
      doc.text('Current Stock', colX[3], tableTop, { width: 100, align: 'center' });

      doc.moveDown(0.5);
      const headerBottom = doc.y;
      doc.moveTo(50, headerBottom).lineTo(545, headerBottom).strokeColor('#e2e8f0').stroke();
      doc.moveDown(0.3);

      for (const item of po.items) {
        const rowTop = doc.y;
        doc.font('Helvetica').fillColor('#1e293b').fontSize(9);
        doc.text(item.product_title || 'Unknown', colX[0], rowTop, { width: 210 });
        doc.text(item.variant_title || '—', colX[1], rowTop, { width: 110 });
        doc.text(String(item.qty || 0), colX[2], rowTop + 1, { width: 75, align: 'center' });
        doc.text(String(item.current_stock ?? '?'), colX[3], rowTop + 1, { width: 100, align: 'center' });
        doc.moveDown(0.8);

        if (doc.y > 700) doc.addPage();
      }
    }

    doc.moveDown(0.8);
    const tableEnd = doc.y;
    doc.moveTo(50, tableEnd).lineTo(545, tableEnd).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);

    if (po.notes) {
      doc.font('Helvetica-Bold').fillColor('#1e293b').fontSize(10).text('Notes:');
      doc.font('Helvetica').fillColor('#64748b').fontSize(9).text(po.notes);
      doc.moveDown(1);
    }

    doc.moveDown(2);
    doc.fontSize(8).font('Helvetica').fillColor('#64748b')
      .text('Generated by Superare Ops', 50, doc.y, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('PDF generation error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal error generating PDF' });
    }
  }
};
